<?php
declare(strict_types=1);require __DIR__.'/core.php';begin_session();$error='';$notice='';
try{if($_SERVER['REQUEST_METHOD']==='POST'){handle_action(valid_text($_POST['action']??'',40));header('Location: index.php?tab='.urlencode(valid_text($_POST['tab']??'menu',30)).'&saved=1',true,303);exit;}}catch(Throwable $e){$error=$e->getMessage();http_response_code(in_array($e->getCode(),[400,401,403,409,429,503],true)?$e->getCode():400);}
try{$state=tx(fn($s)=>$s,false);$user=current_user($state);}catch(Throwable $e){$state=null;$user=null;$error=$e->getMessage();}
$tab=in_array($_GET['tab']??'',['menu','products','users','password','history'],true)?$_GET['tab']:'menu';if($user&&$user['must_change'])$tab='password';
$groups=['wochenkarte'=>'Wochenkarte','klassiker'=>'Unsere Klassiker','weisswein'=>'Weißwein','rotwein'=>'Rotwein'];
function hidden_fields(string $action,string $tab):void{global $state;echo '<input type="hidden" name="csrf" value="'.h($_SESSION['csrf']).'"><input type="hidden" name="action" value="'.h($action).'"><input type="hidden" name="tab" value="'.h($tab).'"><input type="hidden" name="revision" value="'.h($state['revision']??0).'">';}
function euro(int $n):string{return number_format($n/100,2,',','');}
function field(string $label,string $name,string $value='',string $type='text',bool $required=true):void{echo '<label class="field">'.h($label).'<input type="'.h($type).'" name="'.h($name).'" value="'.h($value).'"'.($required?' required':'').' '.($type==='password'?'autocomplete="new-password"':'').' maxlength="2000"></label>';}
?><!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Verwaltung · Vineria del Este</title><link rel="stylesheet" href="../assets/site.css"><style>.manage{max-width:1100px;margin:35px auto;padding:0 22px 70px}.manage h1{font-size:55px;line-height:1.08}.manage h2{font-size:32px}.manage-nav{display:flex;flex-wrap:wrap;gap:20px;padding:18px 0;margin-bottom:24px;border-block:1px solid var(--line);font-size:13px}.manage table{width:100%;border-collapse:collapse;margin:20px 0}.manage th,.manage td{padding:12px 9px;text-align:left;border-bottom:1px solid var(--line);font-size:12px;vertical-align:top}.manage table input:not([type=checkbox]),.manage textarea{width:100%;min-width:0;padding:9px;border:1px solid var(--line);background:var(--paper);font:14px Arial}.manage textarea{min-height:65px}.manage .field{display:block;font-size:12px;margin-bottom:18px}.manage .field input,.manage .field select{display:block;width:100%;padding:11px;margin-top:7px;background:var(--paper);border:1px solid var(--line);color:var(--ink)}.manage-grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.manage .notice.error{border-color:#922}.manage .account{border:1px solid var(--line);padding:23px;margin-bottom:22px}.manage .account .btn{margin-top:10px}.inline{display:inline}.logout{float:right}.price-input{max-width:100px}.manage .draft-state{padding:12px 0;font-size:12px;color:var(--muted)}@media(max-width:650px){.manage h1{font-size:43px}.manage-grid{grid-template-columns:1fr}.manage table,.manage tbody,.manage tr,.manage td{display:block}.manage th{display:none}.manage tr{border-bottom:1px solid var(--line);padding:12px 0}.manage td{border:0;padding:7px 0}.price-input{max-width:100%}.manage-nav{gap:15px}.logout{float:none;margin-top:14px}}</style></head><body><main class="manage"><p class="eyebrow">Vineria del Este · Team</p><h1>Einfach verwalten.</h1><a class="text-link" href="../index.html">Restaurant ansehen ↗</a>
<?php if($error):?><p class="notice error" role="alert"><?=h($error)?></p><?php endif;?>
<?php if(!$user):?>
 <section style="max-width:460px;margin-top:30px"><h2>Team-Zugang</h2><form method="post"><?php hidden_fields('login','menu');field('Benutzername','username');field('Passwort','password','','password');?><button class="btn">Anmelden →</button></form><p class="note">Ein eigener Zugang für jedes Teammitglied. Passwörter werden nicht angezeigt.</p></section>
<?php else:?>
 <form method="post" class="logout"><?php hidden_fields('logout','menu');?><button class="btn outline">Abmelden</button></form><p class="draft-state">Angemeldet als <strong><?=h($user['name'])?></strong> · <?=h($user['role'])?> · Stand <?=h($state['revision'])?></p>
 <?php if(isset($_GET['saved'])):?><p class="notice" role="status">Änderung gespeichert.</p><?php endif;?>
 <nav class="manage-nav" aria-label="Team-Bereiche"><?php foreach(['menu'=>'Speisekarten','products'=>'Produkte','users'=>'Team & Zugänge','password'=>'Mein Passwort','history'=>'Sicherungen']as$k=>$label):if($k==='users'&&$user['role']!=='admin')continue;?><a href="?tab=<?=h($k)?>" <?=$tab===$k?'aria-current="page"':''?>><?=h($label)?></a><?php endforeach;?></nav>
 <?php if($user['must_change']):?><p class="notice">Bitte das gemeinsame Startpasswort jetzt durch ein eigenes Passwort ersetzen. Erst danach lassen sich Inhalte bearbeiten.</p><?php endif;?>
 <?php if($tab==='password'):?>
 <section style="max-width:520px"><h2>Mein Passwort ändern</h2><form method="post"><?php hidden_fields('password','password');field('Aktuelles Passwort','old','','password');field('Neues Passwort · mindestens 12 Zeichen','new','','password');field('Neues Passwort wiederholen','confirm','','password');?><button class="btn">Passwort ändern</button></form><p class="note">Nach einer Änderung werden andere Sitzungen dieses Kontos ungültig.</p></section>
 <?php elseif($tab==='menu'):$cat=array_key_exists($_GET['category']??'',$groups)?$_GET['category']:'wochenkarte';?>
 <h2>Speisekarten</h2><nav class="manage-nav"><?php foreach($groups as$k=>$label):?><a href="?tab=menu&amp;category=<?=h($k)?>"><?=h($label)?></a><?php endforeach;?></nav><form method="post"><?php hidden_fields('save_menu','menu');?><input type="hidden" name="category" value="<?=h($cat)?>"><h3><?=h($groups[$cat])?></h3><p class="note">Namen, Beschreibungen und Preise direkt ändern. Neue Gerichte in den leeren Zeilen eintragen. „Anzeigen“ deaktiviert ein Gericht, ohne den Entwurf zu löschen.</p><table><thead><tr><th>Gericht & Beschreibung</th><th>Preis €</th><th>Anzeigen</th></tr></thead><tbody><?php $rows=array_merge($state['catalog']['menu'][$cat],[['','',0,true],['','',0,true],['','',0,true]]);foreach($rows as$i=>$r):?><tr><td><label><span class="note">Name</span><input name="name[<?=$i?>]" value="<?=h($r[0])?>" maxlength="200"></label><label><span class="note">Beschreibung Deutsch</span><textarea name="description[<?=$i?>]" maxlength="2000"><?=h($r[1])?></textarea></label></td><td><label>Preis €<input class="price-input" name="price[<?=$i?>]" value="<?=h(euro($r[2]))?>" inputmode="decimal"></label></td><td><label><input type="checkbox" name="enabled[<?=$i?>]" <?=($r[3]??true)?'checked':''?>> Sichtbar</label></td></tr><?php endforeach;?></tbody></table><button class="btn">Entwurf speichern</button></form>
 <?php elseif($tab==='products'):$selected=null;foreach($state['catalog']['products']as$p)if($p['id']===($_GET['edit']??''))$selected=$p;$p=$selected??['id'=>'','name'=>'','brand'=>'','description'=>'','pack'=>'','note'=>'','year'=>'','category'=>'conservas','unit'=>'g','amount'=>100,'price'=>0,'case'=>0,'casePrice'=>0,'stock'=>0,'source'=>'','pickup'=>false,'active'=>true];?>
 <h2>Produkte</h2><p><a class="btn outline" href="?tab=products">+ Neues Produkt</a></p><table><thead><tr><th>Produkt</th><th>Preis</th><th>Status</th></tr></thead><tbody><?php foreach($state['catalog']['products']as$item):?><tr><td><a href="?tab=products&amp;edit=<?=urlencode($item['id'])?>"><?=h($item['name'])?></a></td><td><?=h(euro($item['price']))?> €</td><td><?=($item['active']??true)?'Sichtbar':'Versteckt'?></td></tr><?php endforeach;?></tbody></table><section class="account"><h3><?=$selected?'Produkt bearbeiten':'Neues Produkt'?></h3><form method="post"><?php hidden_fields('save_product','products');?><div class="manage-grid"><?php field('Artikel-ID / Seitenadresse','product_id',$p['id']);field('Name','name',$p['name']);field('Marke / Region','brand',$p['brand']);field('Format, z. B. 0,75 l oder 110 g','pack',$p['pack']);?><label class="field">Kategorie<select name="category"><?php foreach(['conservas'=>'Konserven','embutidos'=>'Wurst & Cecina','weisswein'=>'Weißwein','rotwein'=>'Rotwein']as$k=>$v):?><option value="<?=h($k)?>" <?=$p['category']===$k?'selected':''?>><?=h($v)?></option><?php endforeach;?></select></label><label class="field">Mengeneinheit<select name="unit"><option value="g" <?=$p['unit']==='g'?'selected':''?>>Gramm</option><option value="ml" <?=$p['unit']==='ml'?'selected':''?>>Milliliter</option></select></label><?php field('Inhalt in g / ml','amount',(string)$p['amount'],'number');field('Einzelpreis €','price',euro($p['price']));field('Flaschen / Einheiten pro Karton · 0 = kein Karton','case',(string)$p['case'],'number');field('Kartonpreis €','casePrice',euro($p['casePrice']));field('Bestand in einzelnen Einheiten','stock',(string)($p['stock']??0),'number');field('Jahrgang · optional','year',$p['year']??'','text',false);?></div><label class="field">Beschreibung<textarea name="description" maxlength="2000"><?=h($p['description'])?></textarea></label><label class="field">Zutaten, Allergene, Lagerung und Hinweise<textarea name="note" maxlength="5000"><?=h($p['note']??'')?></textarea></label><?php field('HTTPS-Referenz · optional','source',$p['source']??'','url',false);?><p><label><input type="checkbox" name="pickup" <?=$p['pickup']?'checked':''?>> Nur Abholung</label></p><p><label><input type="checkbox" name="active" <?=($p['active']??true)?'checked':''?>> Im Shop anzeigen</label></p><button class="btn">Produktentwurf speichern</button></form></section>
 <?php elseif($tab==='users'&&$user['role']==='admin'):?>
 <h2>Team & Zugänge</h2><p class="note">Jedes Konto hat ein eigenes Passwort. Ein neues Startpasswort wird nie im Klartext gespeichert. Eine Änderung sperrt alte Sitzungen.</p><?php $accounts=array_values($state['users']);$accounts[]=['id'=>'','name'=>'','role'=>'editor','active'=>true];foreach($accounts as$a):?><section class="account"><h3><?=h($a['name']?:'Neues Teammitglied')?></h3><form method="post"><?php hidden_fields('user_save','users');?><input type="hidden" name="user_id" value="<?=h($a['id'])?>"><div class="manage-grid"><?php field('Benutzername','user_name',$a['name']);field($a['id']?'Neues Startpasswort · leer = unverändert':'Startpasswort · mindestens 12 Zeichen','initial_password','','password',!$a['id']);?><label class="field">Berechtigung<select name="role"><option value="editor" <?=$a['role']==='editor'?'selected':''?>>Redaktion · Inhalte bearbeiten</option><option value="admin" <?=$a['role']==='admin'?'selected':''?>>Administrator · veröffentlichen & Team</option></select></label><label class="field"><input type="checkbox" name="active" <?=$a['active']?'checked':''?>> Zugang aktiv</label></div><button class="btn">Konto speichern</button></form></section><?php endforeach;?>
 <?php elseif($tab==='history'):?>
 <h2>Sicherungen</h2><p>Die letzten zwölf Inhaltsstände bleiben erhalten. Wiederherstellung ändert zunächst nur den Entwurf.</p><?php foreach(array_reverse($state['history'],true)as$i=>$snap):?><form method="post" class="account"><?php hidden_fields('restore','history');?><input type="hidden" name="snapshot" value="<?=$i?>"><p><?=h($snap['at'])?></p><button class="btn outline">Als Entwurf wiederherstellen</button></form><?php endforeach;?>
 <?php endif;?>
 <?php if(!$user['must_change']&&$user['role']==='admin'):?><section class="account" style="margin-top:40px"><h2>Beide Webbereiche aktualisieren</h2><p>Gespeicherte Entwürfe gleichzeitig für Restaurant und Tienda veröffentlichen. Der Shop bleibt weiterhin im Testmodus; dadurch werden keine echten Zahlungen aktiviert.</p><form method="post"><?php hidden_fields('publish',$tab);?><button class="btn">Restaurant & Shop veröffentlichen</button></form><p class="note">Zuletzt veröffentlicht: <?=h($state['published_at']??'Noch nicht')?></p></section><?php endif;?>
<?php endif;?></main></body></html>
