'use strict';
(()=>{
 const node=document.getElementById('vde-shared-data');if(!node)return;
 const config=JSON.parse(node.textContent),key='vineria-shared-content-preview',draftKey=key+'-draft',menuKey='vineria-management-local-preview-v1';
 const clone=x=>JSON.parse(JSON.stringify(x));
 function load(k,fallback){try{const x=JSON.parse(localStorage.getItem(k)||'null');return x&&x.schema===1?x:clone(fallback)}catch{return clone(fallback)}}
 function published(){return config.mode==='review'?load(key,config.extras):clone(config.extras)}
 function store(k,v){try{localStorage.setItem(k,JSON.stringify(v));return true}catch{return false}}
 function safeURL(value,allowImage=false){if(value==='@shop')return config.shop||'#';if(allowImage&&/^data:image\/(jpeg|png|webp);base64,[A-Za-z0-9+/=]+$/.test(value))return value;try{const url=new URL(value,config.root);if(url.protocol==='https:'||url.origin===location.origin&&url.protocol==='http:')return url.href;if(location.protocol==='file:'&&url.protocol==='file:')return url.href}catch{}return ''}
 function tag(type,cls,text){const e=document.createElement(type);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;return e}
 function picture(image,alt){const i=tag('img');i.src=safeURL(image,true);i.alt=alt||'';i.loading='lazy';i.decoding='async';return i}
 const news=document.querySelector('[data-vde-news]'),ig=document.querySelector('[data-vde-instagram]');
 function liveNews(x){const now=Date.now();return (x.news||[]).filter(n=>n.enabled&&(config.mode==='review'||!n.example)&&(!n.starts_at||Date.parse(n.starts_at)<=now)&&(!n.ends_at||Date.parse(n.ends_at)>now)).slice(0,x.news_limit===1?1:2)}
 function render(){const x=published();if(news){const items=liveNews(x);news.hidden=!x.news_enabled||items.length===0;const grid=news.querySelector('.vde-news-grid');grid.replaceChildren();for(const n of items){const card=tag('article','vde-news-card'+(!n.image?' vde-text-only':''));if(n.image&&safeURL(n.image,true))card.append(picture(n.image,n.image_alt));const copy=tag('div');if(n.example)copy.append(tag('span','vde-example','GESTALTUNGSBEISPIEL · kein angekündigter Termin'));copy.append(tag('h3','',n.title),tag('p','',n.text));const href=safeURL(n.button_url||'');if(href&&n.button_label){const a=tag('a','',n.button_label+' ↗');a.href=href;if(new URL(href,location.href).origin!==location.origin){a.target='_blank';a.rel='noopener noreferrer'}copy.append(a)}card.append(copy);grid.append(card)}}if(ig){const data=x.instagram||{};ig.hidden=!data.enabled;const grid=ig.querySelector('.vde-instagram-grid');grid.replaceChildren();const limit=data.count===8?8:4;for(const item of (data.items||[]).slice(0,limit)){const src=safeURL(item.image,true),href=safeURL(item.permalink);if(!src||!href)continue;const a=tag('a');a.href=href;a.target='_blank';a.rel='noopener noreferrer';a.append(picture(item.image,item.alt));grid.append(a)}const note=ig.querySelector('.vde-source-note');note.textContent=data.display_mode==='instagram_cache'?'Bilder aus @vineria.del.este. '+(data.connected?'Automatisch aktualisiert.':'Ausgewählte Beiträge für die Vorschau; automatische Verbindung noch nicht aktiviert.'):'Galerievorschau mit eigenen Restaurantfotos. Der automatische Instagram-Feed wird nach der Kontoverbindung verwendet.';if(limit>(data.items||[]).length)note.textContent+=' Angezeigt werden die vorhandenen '+(data.items||[]).length+' Bilder; es werden keine Bilder doppelt eingesetzt.'}renderMenu()}
 function renderMenu(){const holder=document.querySelector('[data-vde-menu]');if(!holder)return;let menu=config.menu;try{const local=JSON.parse(localStorage.getItem(menuKey)||'null');if(config.mode==='review'&&local?.menu)menu=Object.fromEntries(Object.entries(local.menu).map(([k,v])=>[k,v.filter(r=>r.visible!==false).map(r=>[r.name,r.description,r.price])]))}catch{}for(const [cat,rows]of Object.entries(menu||{})){const panel=holder.querySelector('[data-menu-category="'+cat+'"] .vde-menu-grid');if(!panel)continue;panel.replaceChildren();for(const row of rows){const a=tag('article','vde-menu-item');a.dataset.menuItem='';a.append(tag('h4','',row[0]),tag('span','vde-menu-price',(Number(row[2])/100).toLocaleString('de-DE',{style:'currency',currency:'EUR'})),tag('p','',row[1]));panel.append(a)}}}
 const tabs=[...document.querySelectorAll('[data-menu-tab]')];function setTab(button,focus=false){tabs.forEach(b=>{const selected=b===button;b.setAttribute('aria-selected',String(selected));b.tabIndex=selected?0:-1;document.getElementById(b.getAttribute('aria-controls')).hidden=!selected});if(focus)button.focus()}
 tabs.forEach((b,i)=>{b.addEventListener('click',()=>setTab(b));b.addEventListener('keydown',e=>{if(!['ArrowRight','ArrowLeft','Home','End'].includes(e.key))return;e.preventDefault();const target=e.key==='Home'?0:e.key==='End'?tabs.length-1:(i+(e.key==='ArrowRight'?1:tabs.length-1))%tabs.length;setTab(tabs[target],true)})});if(tabs.length)setTab(tabs[0]);
 addEventListener('storage',e=>{if([key,menuKey].includes(e.key))render()});render();
 const editor=document.getElementById('extra-management');if(!editor)return;
 let draft=load(draftKey,published()),selected=draft.news[0]?.id||'';
 const $=id=>editor.querySelector('#'+id),status=$('extra-status');
 function message(t){status.textContent=t}
 function saveDraft(){store(draftKey,draft);message('Entwurf geändert. Mit „Für alle Entwürfe übernehmen“ in diesem Browser anzeigen.')}
 function commit(){if(!store(key,draft)){message('Speicher voll oder gesperrt. Bitte ein kleineres Bild verwenden.');return}store(draftKey,draft);render();message('Für alle sieben Entwürfe in diesem Browser übernommen. Keine öffentliche Veröffentlichung.');updateConnection()}
 function quick(update){const p=published();update(p);if(store(key,p)){store(draftKey,draft);render();message('Einstellung für alle sieben Entwürfe in diesem Browser geändert.')}else message('Speicherung nicht verfügbar.')}
 function record(){return draft.news.find(n=>n.id===selected)}
 function paintList(){const sel=$('news-select');sel.replaceChildren();for(const n of draft.news){const o=tag('option','',(n.enabled?'Sichtbar: ':'Ausgeblendet: ')+(n.title||'Neue Nachricht'));o.value=n.id;sel.append(o)}if(!draft.news.some(n=>n.id===selected))selected=draft.news[0]?.id||'';sel.value=selected;paintRecord()}
 function paintRecord(){const n=record();$('news-form').hidden=!n;if(!n)return;for(const f of ['title','text','image_alt','button_label','button_url','starts_at','ends_at'])$('news-'+f).value=n[f]||'';$('news-active').checked=!!n.enabled;$('news-example').checked=!!n.example;const im=$('news-image-preview');im.hidden=!n.image;if(n.image)im.src=safeURL(n.image,true);$('news-image').value=''}
 function updateConnection(){const g=draft.instagram;$('instagram-enabled').checked=!!g.enabled;$('instagram-count').value=String(g.count);$('instagram-connection').textContent=g.connected?'Verbunden mit @'+g.username:'@'+g.username+' · Automatische Verbindung noch nicht aktiviert';$('instagram-sync').textContent=g.last_sync?'Letzte Aktualisierung: '+new Date(g.last_sync).toLocaleString('de-DE'):'Noch keine automatische Synchronisierung';$('instagram-loaded').textContent=(g.items||[]).length+' Bilder für die Vorschau verfügbar. Bei Auswahl von acht werden nie Bilder doppelt angezeigt.'}
 $('news-enabled').checked=!!draft.news_enabled;$('news-limit').value=String(draft.news_limit);
 $('news-enabled').onchange=e=>{draft.news_enabled=e.target.checked;quick(p=>p.news_enabled=draft.news_enabled)};
 $('news-limit').onchange=e=>{draft.news_limit=Number(e.target.value);quick(p=>p.news_limit=draft.news_limit)};
 $('news-select').onchange=e=>{selected=e.target.value;paintRecord()};
 $('news-add').onclick=()=>{const n={id:'news-'+Date.now().toString(36),title:'Neue Nachricht',text:'',image:'',image_alt:'',enabled:false,example:false,button_label:'',button_url:'',starts_at:'',ends_at:''};draft.news.push(n);selected=n.id;paintList();saveDraft()};
 for(const f of ['title','text','image_alt','button_label','button_url','starts_at','ends_at'])$('news-'+f).oninput=e=>{if(record()){record()[f]=e.target.value;saveDraft()}};
 $('news-active').onchange=e=>{if(!record())return;record().enabled=e.target.checked;const id=selected,enabled=e.target.checked;quick(p=>{const n=p.news.find(a=>a.id===id);if(n)n.enabled=enabled});paintList()};
 $('news-example').onchange=e=>{if(record()){record().example=e.target.checked;saveDraft()}};
 $('news-delete').onclick=()=>{if(!record()||!confirm('Diese Nachricht aus dem Entwurf entfernen?'))return;draft.news=draft.news.filter(n=>n.id!==selected);paintList();saveDraft()};
 $('news-up').onclick=()=>{const i=draft.news.findIndex(n=>n.id===selected);if(i>0){[draft.news[i-1],draft.news[i]]=[draft.news[i],draft.news[i-1]];paintList();saveDraft()}};
 $('news-remove-image').onclick=()=>{if(record()){record().image='';paintRecord();saveDraft()}};
 $('news-image').onchange=async e=>{const f=e.target.files[0];if(!f)return;if(!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size>8e6){message('Bitte JPG, PNG oder WebP bis 8 MB auswählen.');return}try{const bitmap=await createImageBitmap(f),scale=Math.min(1,1400/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);record().image=canvas.toDataURL('image/jpeg',.84);bitmap.close();paintRecord();saveDraft()}catch{message('Dieses Bild konnte nicht verarbeitet werden.')}};
 $('instagram-enabled').onchange=e=>{draft.instagram.enabled=e.target.checked;quick(p=>p.instagram.enabled=draft.instagram.enabled)};
 $('instagram-count').onchange=e=>{draft.instagram.count=Number(e.target.value);quick(p=>p.instagram.count=draft.instagram.count);updateConnection()};
 $('extra-save').onclick=commit;$('extra-reset').onclick=()=>{if(!confirm('Lokale Nachrichten- und Instagram-Teständerungen zurücksetzen?'))return;localStorage.removeItem(key);localStorage.removeItem(draftKey);draft=clone(config.extras);selected=draft.news[0]?.id||'';$('news-enabled').checked=draft.news_enabled;$('news-limit').value=String(draft.news_limit);paintList();updateConnection();render();message('Gemeinsame Ausgangsdaten wiederhergestellt.')};
 editor.querySelectorAll('[data-extra-tab]').forEach(b=>b.onclick=()=>{editor.querySelectorAll('[data-extra-tab]').forEach(x=>x.setAttribute('aria-selected',String(x===b)));editor.querySelectorAll('[data-extra-panel]').forEach(x=>x.hidden=x.dataset.extraPanel!==b.dataset.extraTab)});
 paintList();updateConnection();
})();
