'use strict';
(()=>{const api=window.VdeReview,app=document.getElementById('vde-control');if(!api||!app)return;let data=api.state(),tab='menu',chosen=data.sections[0]?.id,undo=null;const e=api.esc;
 const uid=p=>p+'-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7);
 function setState(text){document.getElementById('control-status').textContent=text;}
 function save(){try{api.save(data);setState('In diesem Browser für alle acht Entwürfe übernommen. Keine öffentliche Veröffentlichung.');}catch{setState('Speicher voll oder gesperrt. Bitte ein kleineres Bild wählen.');}}
 function dirty(){setState('Ungespeicherte Änderungen. „Übernehmen“ aktualisiert die Entwürfe in diesem Browser.');}
 function remove(array,i,label){if(!confirm(label+' entfernen? Mit „Rückgängig“ wiederherstellbar.'))return;undo=JSON.parse(JSON.stringify(data));array.splice(i,1);draw();save();}
 function value(row,key,label,type='text'){return `<label>${e(label)}<input data-key="${e(key)}" type="${type}" value="${e(type==='number'?(key.toLowerCase().includes('price')?Number(row[key]||0)/100:row[key]??0):row[key]||'')}" ${type==='number'?'min="0" step="'+(key.toLowerCase().includes('price')?'.01':'1')+'"':''}></label>`;}
 const toggle=(row,key,label)=>`<label class="control-check"><input type="checkbox" data-key="${key}" ${row[key]!==false?'checked':''}>${label}</label>`;
 const del=(label)=>`<button type="button" class="control-delete" data-delete aria-label="${e(label)} entfernen" title="Entfernen">×</button>`;
 const imageFields=row=>`<details class="image-controls"><summary>Foto / Grafik auswählen</summary>${row.image?`<img class="control-thumb" src="${e(api.url(row.image))}" alt="Vorschaubild">`:''}<label>Hochladen<input data-upload type="file" accept="image/png,image/jpeg,image/webp"></label><label>Vorhandenes Bild<select data-image><option value="">Bild auswählen …</option><option value="assets/approved/paella-halftone.webp">Paella · Fotokopie</option><option value="assets/approved/pulpo-halftone.webp">Pulpo · Fotokopie</option><option value="assets/approved/boquerones-halftone.webp">Boquerones · Fotokopie</option><option value="assets/approved/paella-color.webp">Paella · Farbe</option><option value="assets/approved/pulpo-color.webp">Pulpo · Farbe</option><option value="assets/approved/boquerones-color.webp">Boquerones · Farbe</option><option value="assets/terrasse.webp">Originalfoto · Terrasse</option></select></label><button type="button" data-remove-image>Foto entfernen</button></details>`;
 function wireRows(rows){app.querySelectorAll('[data-row]').forEach(box=>{const i=+box.dataset.row,row=rows[i];box.querySelectorAll('[data-key]').forEach(input=>input.oninput=()=>{const k=input.dataset.key;row[k]=input.type==='checkbox'?input.checked:input.type==='number'?Math.max(0,Math.round(Number(input.value||0)*(k.toLowerCase().includes('price')?100:1))):input.value;dirty();if(input.type==='checkbox')save();});box.querySelector('[data-delete]')?.addEventListener('click',()=>remove(rows,i,row.name||row.title||row.label||'Eintrag'));box.querySelector('[data-image]')?.addEventListener('change',ev=>{if(ev.target.value){row.image=ev.target.value;draw();dirty();}});box.querySelector('[data-remove-image]')?.addEventListener('click',()=>{row.image='';draw();dirty();});box.querySelector('[data-upload]')?.addEventListener('change',async ev=>{const file=ev.target.files[0];if(!file)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>8000000){setState('Bitte PNG, JPG oder WebP bis 8 MB verwenden.');return;}try{const b=await createImageBitmap(file),scale=Math.min(1,1000/Math.max(b.width,b.height)),c=document.createElement('canvas');c.width=Math.round(b.width*scale);c.height=Math.round(b.height*scale);c.getContext('2d').drawImage(b,0,0,c.width,c.height);row.image=c.toDataURL('image/webp',.85);b.close();draw();dirty();}catch{setState('Bild konnte nicht gelesen werden.');}});box.querySelectorAll('[data-move]').forEach(b=>b.onclick=()=>{const j=i+Number(b.dataset.move);if(j<0||j>=rows.length)return;[rows[i],rows[j]]=[rows[j],rows[i]];draw();dirty();});});}
 function draw(){document.querySelectorAll('[data-control-tab]').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.controlTab===tab)));document.getElementById('control-add').hidden=['instagram','team'].includes(tab);let rows=[];
 if(tab==='menu'){chosen=data.sections.some(s=>s.id===chosen)?chosen:data.sections[0]?.id;rows=data.sections.find(s=>s.id===chosen)?.items||[];app.innerHTML='<label>Menübereich<select id="control-category">'+data.sections.map(s=>`<option value="${e(s.id)}" ${s.id===chosen?'selected':''}>${e(s.label)}</option>`).join('')+'</select></label>'+rows.map((r,i)=>`<article class="control-row" data-row="${i}"><div>${value(r,'name','Gericht')}<label>Beschreibung<textarea data-key="description">${e(r.description)}</textarea></label></div>${value(r,'price','Preis (€)','number')}${toggle(r,'visible','Sichtbar')}${del(r.name)}</article>`).join('');app.querySelector('#control-category').onchange=ev=>{chosen=ev.target.value;draw();};}
 else if(tab==='sections'){rows=data.sections;app.innerHTML='<p>Diese Namen und ihre Reihenfolge werden als Reiter der Speisekarte übernommen. Beim Entfernen eines Bereichs werden auch dessen Einträge entfernt.</p>'+rows.map((r,i)=>`<article class="control-row" data-row="${i}">${value(r,'label','Name des Menübereichs')}${toggle(r,'visible','Sichtbar')}<div class="control-order"><button data-move="-1" aria-label="Bereich nach oben">↑</button><button data-move="1" aria-label="Bereich nach unten">↓</button></div>${del(r.label)}</article>`).join('');}
 else if(tab==='products'){rows=data.products;app.innerHTML=rows.map((r,i)=>`<article class="control-product" data-row="${i}"><div class="control-product-head"><h2>${e(r.name)}</h2>${toggle(r,'visible','Sichtbar')}${del(r.name)}</div><div class="control-grid">${value(r,'name','Produkt')}${value(r,'price','Preis (€)','number')}${value(r,'brand','Marke / Herkunft')}${value(r,'category','Kategorie')}<label>Beschreibung<textarea data-key="description">${e(r.description)}</textarea></label>${value(r,'pack','Format / Packung')}${value(r,'amount','Inhalt (g oder ml)','number')}<label>Einheit<select data-key="unit"><option value="g" ${r.unit==='g'?'selected':''}>g</option><option value="ml" ${r.unit==='ml'?'selected':''}>ml</option></select></label>${value(r,'case','Einheiten pro Karton','number')}${value(r,'casePrice','Kartonpreis (€)','number')}${toggle(r,'pickup','Nur Abholung')}${imageFields(r)}</div></article>`).join('');}
 else if(tab==='news'){rows=data.news.items;app.innerHTML=`<div class="control-grid"><label class="control-check"><input id="news-show" type="checkbox" ${data.news.enabled?'checked':''}>Nachrichtenblock anzeigen</label><label>Anzahl<select id="news-limit"><option value="1" ${data.news.limit===1?'selected':''}>Eine Nachricht</option><option value="2" ${data.news.limit===2?'selected':''}>Bis zu zwei Nachrichten</option></select></label></div>`+rows.map((r,i)=>`<article class="control-product" data-row="${i}"><div class="control-product-head"><h2>${e(r.title||'Neue Nachricht')}</h2>${toggle(r,'visible','Sichtbar')}${del(r.title)}</div><div class="control-grid">${value(r,'title','Überschrift')}<label>Text, Datum, Uhrzeit und Details<textarea data-key="text" rows="5">${e(r.text)}</textarea></label>${value(r,'linkLabel','Linktext · optional')}${value(r,'link','Linkadresse · optional')}${value(r,'starts','Anzeigen ab · optional','datetime-local')}${value(r,'ends','Anzeigen bis · optional','datetime-local')}${toggle(r,'example','Gestaltungsbeispiel, kein bestätigter Termin')}${imageFields(r)}</div></article>`).join('');document.getElementById('news-show').onchange=ev=>{data.news.enabled=ev.target.checked;save();};document.getElementById('news-limit').onchange=ev=>{data.news.limit=+ev.target.value;save();};}
 else if(tab==='instagram'){app.innerHTML=`<h2>Instagram am Seitenende.</h2><label class="control-check"><input id="ig-show" type="checkbox" ${data.instagram.enabled?'checked':''}>Galerie anzeigen</label><label>Fotos<select id="ig-count"><option value="4" ${data.instagram.count===4?'selected':''}>4 Fotos</option><option value="8" ${data.instagram.count===8?'selected':''}>8 Fotos</option></select></label><p class="notice">@vineria.del.este ist noch nicht automatisch verbunden. Die einmalige Freigabe erfolgt später über Instagram/Meta auf dem Server. Hier werden eigene vorhandene Fotos als Vorschau benutzt; keine Instagram-Passwörter eingeben. Bei weniger vorhandenen Bildern werden keine Duplikate hinzugefügt.</p>`;document.getElementById('ig-show').onchange=ev=>{data.instagram.enabled=ev.target.checked;save();};document.getElementById('ig-count').onchange=ev=>{data.instagram.count=+ev.target.value;save();};}
 else app.innerHTML='<h2>Team & Zugänge.</h2><p>Buñol und Kraft sind die vorgesehenen Team-Zugänge. Echte Benutzer, Rollen und Passwortänderungen werden im geschützten Joomla-Administrator verwaltet. In dieser öffentlichen Vorschau werden keine aktiven Konten oder Kennwörter eingerichtet.</p>';
 if(!rows.length&&['menu','products','sections','news'].includes(tab))app.insertAdjacentHTML('beforeend','<p>Keine Einträge. Mit „Hinzufügen“ einen Eintrag anlegen.</p>');wireRows(rows);
 }
 document.querySelectorAll('[data-control-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.controlTab;draw();});
 document.getElementById('control-add').onclick=()=>{if(tab==='menu'){const s=data.sections.find(s=>s.id===chosen);if(!s){setState('Bitte zuerst einen Menübereich anlegen.');return;}s.items.push({id:uid('dish'),name:'Neues Gericht',description:'',price:0,visible:true});}if(tab==='sections'){const s={id:uid('cat'),label:'Neuer Bereich',visible:true,items:[]};data.sections.push(s);chosen=s.id;}if(tab==='products')data.products.push({id:uid('produkt'),name:'Neues Produkt',description:'',brand:'',category:'sonstiges',pack:'1 Stück',amount:1,unit:'g',price:0,case:0,casePrice:0,pickup:false,visible:true,image:''});if(tab==='news')data.news.items.push({id:uid('news'),title:'Neue Nachricht',text:'',image:'',visible:true,example:false,starts:'',ends:'',link:'',linkLabel:''});draw();dirty();};
 document.getElementById('control-save').onclick=save;
 document.getElementById('control-undo').onclick=()=>{if(!undo){setState('Keine Löschung zum Wiederherstellen.');return;}data=undo;undo=null;draw();save();};
 document.getElementById('control-reset').onclick=()=>{if(!confirm('Alle lokalen Teständerungen zurücksetzen?'))return;data=api.defaults();api.reset();draw();save();};
 draw();
})();
